"""initial migration

Revision ID: 1be689b48731
Revises: 
Create Date: 2025-11-30 05:04:22.134194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1be689b48731'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('job_description', sa.String(), nullable=True),
    sa.Column('job_employment_type', sa.String(), nullable=True),
    sa.Column('job_apply_link', sa.String(), nullable=True),
    sa.Column('job_apply_is_direct', sa.Boolean(), nullable=True),
    sa.Column('job_is_remote', sa.Boolean(), nullable=True),
    sa.Column('employer_name', sa.String(), nullable=True),
    sa.Column('employer_logo', sa.String(), nullable=True),
    sa.Column('employer_website', sa.String(), nullable=True),
    sa.Column('job_min_salary', sa.Float(), nullable=True),
    sa.Column('job_max_salary', sa.Float(), nullable=True),
    sa.Column('job_salary_period', sa.String(), nullable=True),
    sa.Column('extraction_note', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    # ### end Alembic commands ###
