"""add_job_lat_long_column

Revision ID: 2980442c511c
Revises: 12c5cc67ca93
Create Date: 2025-12-07 14:56:36.343084

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2980442c511c"
down_revision: Union[str, Sequence[str], None] = "12c5cc67ca93"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("jobs", sa.Column("job_latitude", sa.Float(), nullable=True))
    op.add_column("jobs", sa.Column("job_longitude", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("jobs", "job_longitude")
    op.drop_column("jobs", "job_latitude")
    # ### end Alembic commands ###
