"""create_interviews_table

Revision ID: 702918673355
Revises: 86de274686d5
Create Date: 2026-06-13 11:46:57.352514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '702918673355'
down_revision: Union[str, Sequence[str], None] = '86de274686d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create the ENUM types first if they don't exist using DO blocks
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'type') THEN
                CREATE TYPE type AS ENUM ('TECHNICAL', 'BEHAVIORAL', 'HR_SCREENING');
            END IF;
        END
        $$;
    """)
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'result') THEN
                CREATE TYPE result AS ENUM ('EXCELLENT', 'PASSED', 'BORDERLINE', 'NEEDS_IMPROVEMENT', 'FAILED', 'INCOMPLETE');
            END IF;
        END
        $$;
    """)

    interview_type_enum = postgresql.ENUM('TECHNICAL', 'BEHAVIORAL', 'HR_SCREENING', name='type', create_type=False)
    interview_result_enum = postgresql.ENUM('EXCELLENT', 'PASSED', 'BORDERLINE', 'NEEDS_IMPROVEMENT', 'FAILED', 'INCOMPLETE', name='result', create_type=False)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interviews',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', interview_type_enum, nullable=False),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('employer', sa.String(), nullable=True),
    sa.Column('resume_object_key', sa.String(), nullable=True),
    sa.Column('transcripts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', interview_result_enum, nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interviews_user_id'), 'interviews', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interviews_user_id'), table_name='interviews')
    op.drop_table('interviews')
    # ### end Alembic commands ###

    # Drop the ENUM types
    op.execute("DROP TYPE IF EXISTS type")
    op.execute("DROP TYPE IF EXISTS result")
