"""add_job_publisher_to_job_tablle

Revision ID: 783cb5a310a9
Revises: d3ac6e8ebb0b
Create Date: 2025-11-30 08:54:39.042734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '783cb5a310a9'
down_revision: Union[str, Sequence[str], None] = 'd3ac6e8ebb0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('job_publisher', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'job_publisher')
    # ### end Alembic commands ###
