"""add_job_country_to_job_tablle

Revision ID: d3ac6e8ebb0b
Revises: 7ed8f7ed6451
Create Date: 2025-11-30 08:33:25.403196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3ac6e8ebb0b'
down_revision: Union[str, Sequence[str], None] = '7ed8f7ed6451'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('job_country', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'job_country')
    # ### end Alembic commands ###
